
package examples;

public class ContactEditor extends javax.swing.JFrame {
    
    /**
     * Creates new form ContactEditor
     */
    public ContactEditor() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        details = new javax.swing.JDialog();
        namePanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        titleLabel = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        nicknameLabel = new javax.swing.JLabel();
        nicknameField = new javax.swing.JTextField();
        displayFormatLabel = new javax.swing.JLabel();
        displayFormat = new javax.swing.JComboBox();
        emailPanel = new javax.swing.JPanel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        listScrollPane = new javax.swing.JScrollPane();
        emailsList = new javax.swing.JList();
        addEmail = new javax.swing.JButton();
        editEmail = new javax.swing.JButton();
        removeEmail = new javax.swing.JButton();
        mailFormatLabel = new javax.swing.JLabel();
        htmlChoice = new javax.swing.JRadioButton();
        plainTextChoice = new javax.swing.JRadioButton();
        customChoice = new javax.swing.JRadioButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        contactsLabel = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        addContact = new javax.swing.JButton();
        editContact = new javax.swing.JButton();
        removeContact = new javax.swing.JButton();
        contactTablePane = new javax.swing.JScrollPane();
        contactTable = new javax.swing.JTable();

        namePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" Name "));
        firstNameLabel.setText("First Name:");

        lastNameLabel.setText("Last Name:");

        titleLabel.setText("Title:");

        nicknameLabel.setText("Nickname:");

        displayFormatLabel.setText("Display Format:");

        displayFormat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<nickname>", "<first name>", "<first name><last name>", "<last name><first name>" }));

        org.jdesktop.layout.GroupLayout namePanelLayout = new org.jdesktop.layout.GroupLayout(namePanel);
        namePanel.setLayout(namePanelLayout);
        namePanelLayout.setHorizontalGroup(
            namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(namePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(displayFormatLabel)
                    .add(titleLabel)
                    .add(firstNameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(namePanelLayout.createSequentialGroup()
                        .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(titleField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, firstNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(lastNameLabel)
                            .add(nicknameLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lastNameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .add(nicknameField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .add(displayFormat, 0, 331, Short.MAX_VALUE))
                .addContainerGap())
        );
        namePanelLayout.setVerticalGroup(
            namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(namePanelLayout.createSequentialGroup()
                .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(firstNameLabel)
                    .add(lastNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(firstNameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lastNameLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(titleLabel)
                    .add(nicknameField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(nicknameLabel)
                    .add(titleField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(namePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(displayFormatLabel)
                    .add(displayFormat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(" E-mail "));
        emailLabel.setText("E-mail Address:");

        emailsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listScrollPane.setViewportView(emailsList);

        addEmail.setText("Add");

        editEmail.setText("Edit");
        editEmail.setEnabled(false);

        removeEmail.setText("Remove");
        removeEmail.setEnabled(false);

        mailFormatLabel.setText("Mail Format:");

        buttonGroup1.add(htmlChoice);
        htmlChoice.setSelected(true);
        htmlChoice.setText("HTML");
        htmlChoice.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        htmlChoice.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(plainTextChoice);
        plainTextChoice.setText("Plain Text");
        plainTextChoice.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        plainTextChoice.setMargin(new java.awt.Insets(0, 0, 0, 0));

        buttonGroup1.add(customChoice);
        customChoice.setText("Custom");
        customChoice.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        customChoice.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout emailPanelLayout = new org.jdesktop.layout.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(emailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(emailPanelLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(htmlChoice)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(plainTextChoice)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(customChoice))
                    .add(emailPanelLayout.createSequentialGroup()
                        .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(emailPanelLayout.createSequentialGroup()
                                .add(emailLabel)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(emailField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                            .add(listScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(editEmail)
                            .add(addEmail)
                            .add(removeEmail)))
                    .add(mailFormatLabel))
                .addContainerGap())
        );

        emailPanelLayout.linkSize(new java.awt.Component[] {addEmail, editEmail, removeEmail}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(emailPanelLayout.createSequentialGroup()
                .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(emailLabel)
                    .add(emailField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(addEmail))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(emailPanelLayout.createSequentialGroup()
                        .add(editEmail)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(removeEmail))
                    .add(listScrollPane, 0, 144, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mailFormatLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(htmlChoice)
                    .add(plainTextChoice)
                    .add(customChoice))
                .addContainerGap())
        );

        cancelButton.setText("Cancel");

        okButton.setText("OK");

        org.jdesktop.layout.GroupLayout detailsLayout = new org.jdesktop.layout.GroupLayout(details.getContentPane());
        details.getContentPane().setLayout(detailsLayout);
        detailsLayout.setHorizontalGroup(
            detailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, detailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(detailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, emailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, namePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(detailsLayout.createSequentialGroup()
                        .add(okButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(cancelButton)))
                .addContainerGap())
        );

        detailsLayout.linkSize(new java.awt.Component[] {cancelButton, okButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        detailsLayout.setVerticalGroup(
            detailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detailsLayout.createSequentialGroup()
                .addContainerGap()
                .add(namePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(emailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(detailsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(cancelButton)
                    .add(okButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("E-mail Contacts");
        contactsLabel.setFont(new java.awt.Font("Tahoma", 1, 18));
        contactsLabel.setText("Contacts");

        close.setText("Close");

        addContact.setText("Add");

        editContact.setText("Edit");
        editContact.setEnabled(false);

        removeContact.setText("Remove");
        removeContact.setEnabled(false);

        contactTablePane.setViewportView(contactTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(contactTablePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(close)
                            .add(addContact)
                            .add(editContact)
                            .add(removeContact)))
                    .add(contactsLabel))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {addContact, close, editContact, removeContact}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(contactsLabel)
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(addContact)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(editContact)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(removeContact)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 232, Short.MAX_VALUE)
                        .add(close))
                    .add(contactTablePane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContact;
    private javax.swing.JButton addEmail;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton close;
    private javax.swing.JTable contactTable;
    private javax.swing.JScrollPane contactTablePane;
    private javax.swing.JLabel contactsLabel;
    private javax.swing.JRadioButton customChoice;
    private javax.swing.JDialog details;
    private javax.swing.JComboBox displayFormat;
    private javax.swing.JLabel displayFormatLabel;
    private javax.swing.JButton editContact;
    private javax.swing.JButton editEmail;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JList emailsList;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JRadioButton htmlChoice;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JLabel mailFormatLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nicknameField;
    private javax.swing.JLabel nicknameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton plainTextChoice;
    private javax.swing.JButton removeContact;
    private javax.swing.JButton removeEmail;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
    
}
